// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvv3gFmuLBeDsFoHNhVhJw4VOuqMRsG0s',
    appId: '1:1093041322989:web:41a45717a36b1b165385e4',
    messagingSenderId: '1093041322989',
    projectId: 'farmapp-e2145',
    authDomain: 'farmapp-e2145.firebaseapp.com',
    storageBucket: 'farmapp-e2145.firebasestorage.app',
    measurementId: 'G-DPV5G36QXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0JtzWWi50pQd3olxRJtN2eXEULzubTU',
    appId: '1:1093041322989:android:5b521ac48fdb8c2f5385e4',
    messagingSenderId: '1093041322989',
    projectId: 'farmapp-e2145',
    storageBucket: 'farmapp-e2145.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBTiGApbwxs8frQ6j8QVJth_0HniogzU',
    appId: '1:1093041322989:ios:b8418e7e0108bc375385e4',
    messagingSenderId: '1093041322989',
    projectId: 'farmapp-e2145',
    storageBucket: 'farmapp-e2145.firebasestorage.app',
    iosBundleId: 'com.mycompany.farm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBTiGApbwxs8frQ6j8QVJth_0HniogzU',
    appId: '1:1093041322989:ios:e34fa55ef34ff4545385e4',
    messagingSenderId: '1093041322989',
    projectId: 'farmapp-e2145',
    storageBucket: 'farmapp-e2145.firebasestorage.app',
    iosBundleId: 'farm.farm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvv3gFmuLBeDsFoHNhVhJw4VOuqMRsG0s',
    appId: '1:1093041322989:web:b6d86e682dc2f9b85385e4',
    messagingSenderId: '1093041322989',
    projectId: 'farmapp-e2145',
    authDomain: 'farmapp-e2145.firebaseapp.com',
    storageBucket: 'farmapp-e2145.firebasestorage.app',
    measurementId: 'G-QWHDW2EGXL',
  );
}
